### ISSUE TITLE
GET /api/tournaments/:id/movement/:pairNo returns a JSON string for players

### ISSUE THREAD

**Issue by programmablereya** [aragos/tichu-tournament#1]
i.e., it returns `"[{\"name\": \"Player Name\"}]"` instead of `[{"name": "Player Name"}]`.

This means that getting data for the movement detail page is broken, as it can't parse the player list. Returning `.player_list()` instead of `.players` seems to do the trick.

**Comment by teytanna** [comment]
Done!
